import streamlit as st
st.set_page_config(page_title = "Carbon Footprint Calculator")

def calculateCarbonFootprint(
        elec_bill: int,
        water_bill: int,
        # gas_bill: int,
        mileage_car: int,
        short_flights: int,
        long_flights: int,
        recycle_paper: bool,
        recycle_metals: bool
):
    carbon = 0
    carbon += (elec_bill / 0.075) * 0.4716
    carbon += (water_bill / 2.6) * 2.28
    carbon += mileage_car * 0.2
    carbon += short_flights * 1100 * 0.453592
    carbon += long_flights * 4400 * 0.453592
    if recycle_paper == "No": carbon += 184 * 0.453592
    if recycle_metals == "No": carbon += 166 * 0.453592

    return carbon

st.header("What is Carbon footprint?")
st.write("A carbon footprint is a measure of the total\
         greenhouse gas emissions, primarily carbon dioxide,\
        generated by an individual, organization, product, \
        or activity over a specified period. It quantifies \
    the environmental impact of human actions on climate change\
    . These emissions result from activities like energy consumption\
   , transportation, and industrial processes. Reducing one's carbon \
   footprint is crucial for mitigating climate change and involves \
   adopting sustainable practices, using cleaner energy sources, \
   and minimizing waste. It is a key concept in environmental \
   sustainability and a vital step towards a more eco-friendly and resilient future.")

st.text("")
st.text("")
st.text("")
st.text("")
st.text("")
st.text("")

st.header('Calculate your carbon footprint: ',divider="green")
elec_bill = st.number_input("Enter your electricity bill($):")
water_bill = st.number_input("Enter your water bill($):")
mileage_car = st.number_input("Enter your car millage($):") 
short_flights = st.number_input("Enter how much you would usually pay for a short flight($):")
long_flights = st.number_input("Enter how much you would usually pay for a long flight($)") 
recycle_paper = st.radio("Do you recycle paper:",["Yes","No"]) 
recycle_metals = st.radio("Do you recycle metals:",["Yes","No"]) 

if st.button("Submit"):
    st.write( "Your score is",
    calculateCarbonFootprint(elec_bill,
    water_bill,mileage_car,
    short_flights,long_flights,
    recycle_paper,recycle_metals))
    